import { Opportunity, UserProfile } from '@/types/opportunity';

export const opportunities: Opportunity[] = [
  {
    id: '1',
    title: 'AI Client Onboarding for Service Businesses',
    description: 'Build and sell automated client intake systems for service businesses using no-code AI tools. Help accountants, consultants, and agencies qualify leads and collect information 24/7.',
    category: 'ai-opportunities',
    difficulty: 'intermediate',
    timeCommitment: 'part-time',
    estimatedEarning: { min: 2500, max: 6000, period: 'month' },
    startupCost: { min: 50, max: 300 },
    trending: true,
    trendingScore: 94,
    tags: ['AI', 'Automation', 'B2B', 'No-Code'],
    createdAt: '2026-03-20',
    keyInsights: [
      '73% of service businesses lose leads due to slow response times',
      'Make.com + ChatGPT can build systems in under 2 hours',
      'Clients pay $500-1500 setup + $200-500/month maintenance',
    ],
    steps: [
      'Learn Make.com or n8n automation basics (free courses available)',
      'Build a demo system for a specific industry (e.g., wedding photographers)',
      'Reach out to 20 businesses via cold email with personalized Loom video',
      'Offer first client 50% discount in exchange for case study',
      'Create industry-specific templates to speed up future builds',
    ],
    resources: [
      { title: 'Make.com Official Academy', type: 'video' },
      { title: 'AI Prompt Templates for Lead Qualification', type: 'tool' },
      { title: 'Cold Email Scripts for Automation Services', type: 'article' },
    ],
    competition: 'low',
    demandTrend: 'rising',
    riskLevel: 'low',
    whyThisOpportunity: 'Most service businesses still manually handle inquiries and lose leads after hours. AI tools have made it possible to build sophisticated onboarding systems without coding knowledge. The gap between what is possible and what businesses are doing is massive right now.',
    timeToFirstRevenue: '2-4 weeks',
  },
  {
    id: '2',
    title: 'Source Vintage Cameras for Resale',
    description: 'Find undervalued film and vintage digital cameras at estate sales, thrift stores, and online auctions. Resell to collectors and photographers on eBay and specialty forums.',
    category: 'reselling',
    difficulty: 'beginner',
    timeCommitment: 'flexible',
    estimatedEarning: { min: 600, max: 2200, period: 'month' },
    startupCost: { min: 300, max: 800 },
    trending: true,
    trendingScore: 87,
    tags: ['Vintage', 'Cameras', 'Thrift', 'Collectibles'],
    createdAt: '2026-03-18',
    keyInsights: [
      'Film camera prices up 300% since 2020 (especially point-and-shoot)',
      'Estate sales often price cameras at 10-20% of market value',
      'Canon AE-1, Olympus mju-II, and Yashica T4 are consistently in demand',
    ],
    steps: [
      'Download EstateSales.net app and set up local alerts',
      'Study sold listings on eBay to learn fair market prices',
      'Test camera functions using online guides before buying',
      'Take clear, well-lit photos showing all angles and serial numbers',
      'Build reputation by accurately describing condition',
    ],
    resources: [
      { title: 'Film Camera Value Guide by Model', type: 'article' },
      { title: 'Testing Checklist for Film Cameras', type: 'tool' },
      { title: 'r/AnalogCommunity Subreddit', type: 'platform' },
    ],
    competition: 'medium',
    demandTrend: 'rising',
    riskLevel: 'medium',
    whyThisOpportunity: 'The film photography revival is not a fad—it has sustained growth for 5+ years. Supply is fixed (no new film cameras being made) while demand increases as Gen Z discovers film. Estate sales are still pricing based on old perceptions, creating arbitrage opportunities.',
    timeToFirstRevenue: '1-2 weeks',
  },
  {
    id: '3',
    title: 'Weekend Mobile Car Detailing',
    description: 'Offer premium mobile detailing services at homes and offices. Focus on higher-end vehicles and busy professionals who value convenience over price.',
    category: 'local-demand',
    difficulty: 'beginner',
    timeCommitment: 'weekend-only',
    estimatedEarning: { min: 800, max: 2000, period: 'month' },
    startupCost: { min: 400, max: 1200 },
    trending: true,
    trendingScore: 91,
    tags: ['Cars', 'Local Service', 'Weekend', 'Premium'],
    createdAt: '2026-03-15',
    keyInsights: [
      'Mobile detailers charge $150-400 per vehicle vs $80-150 for drive-through',
      'Luxury apartment complexes are ideal marketing partners',
      'Most customers book recurring monthly details once satisfied',
    ],
    steps: [
      'Buy quality starter kit: pressure washer, vacuum, microfibers, quality soap',
      'Practice on your own car and 3 friends cars for before/after photos',
      'Create Instagram account posting transformation content',
      'Post flyers at luxury gyms, apartment complexes, and office parks',
      'Offer referral discounts to turn customers into marketers',
    ],
    resources: [
      { title: 'Mobile Detailing Starter Equipment List', type: 'article' },
      { title: 'Ammonia-Free Interior Cleaning Guide', type: 'video' },
      { title: 'Pricing Calculator for Services', type: 'tool' },
    ],
    competition: 'medium',
    demandTrend: 'rising',
    riskLevel: 'low',
    whyThisOpportunity: 'Car ownership is at record highs, and people are keeping cars longer. Busy professionals will pay 2-3x for convenience. Mobile detailing eliminates the need for a physical location, keeping overhead minimal. Weekend-only scheduling works perfectly for side hustle income.',
    timeToFirstRevenue: '1-3 weeks',
  },
  {
    id: '4',
    title: 'Bookkeeping for Trades Businesses',
    description: 'Provide monthly bookkeeping for plumbers, electricians, and HVAC contractors. Most trade businesses are behind on finances and need help catching up.',
    category: 'freelancing',
    difficulty: 'intermediate',
    timeCommitment: 'part-time',
    estimatedEarning: { min: 2000, max: 5000, period: 'month' },
    startupCost: { min: 0, max: 500 },
    trending: true,
    trendingScore: 89,
    tags: ['Finance', 'Trades', 'Recurring Revenue', 'B2B'],
    createdAt: '2026-03-12',
    keyInsights: [
      '67% of small trade businesses have messy or incomplete books',
      'Standard rate: $300-800/month per client for basic bookkeeping',
      '5 clients at $400/month = $24,000/year with 10-15 hours weekly work',
    ],
    steps: [
      'Complete QuickBooks Online certification (free, takes 2-3 weeks)',
      'Learn construction-specific bookkeeping (job costing, COGS tracking)',
      'Join local contractors Facebook groups and offer free financial health check',
      'Target businesses with 2-10 employees—they need help but cannot afford full-time staff',
      'Set up automated monthly reporting system to reduce ongoing work',
    ],
    resources: [
      { title: 'QuickBooks Online Certification', type: 'video' },
      { title: 'Trades Bookkeeping Templates', type: 'tool' },
      { title: 'Pricing Guide for Bookkeeping Services', type: 'article' },
    ],
    competition: 'low',
    demandTrend: 'rising',
    riskLevel: 'low',
    whyThisOpportunity: 'Trade businesses are booming but owners are technicians, not accountants. They consistently fail at financial management. Unlike general bookkeeping, specializing in trades allows you to charge premium rates and build efficient systems that serve multiple similar clients.',
    timeToFirstRevenue: '4-6 weeks',
  },
  {
    id: '5',
    title: 'Niche Notion Template Store',
    description: 'Create and sell specialized Notion templates for underserved niches. Unlike generic productivity templates, focus on specific workflows like podcast production or rental property management.',
    category: 'online-business',
    difficulty: 'beginner',
    timeCommitment: 'flexible',
    estimatedEarning: { min: 400, max: 3500, period: 'month' },
    startupCost: { min: 0, max: 100 },
    trending: true,
    trendingScore: 85,
    tags: ['Digital Products', 'Notion', 'Passive Income', 'Templates'],
    createdAt: '2026-03-10',
    keyInsights: [
      'Top niche templates earn $2,000-8,000/month with no ongoing work',
      'YouTube tutorials drive 70% of template sales',
      'Update templates quarterly and email existing customers for recurring revenue',
    ],
    steps: [
      'Choose a niche you understand deeply (e.g., freelance writing, wedding planning)',
      'Research existing templates in your niche and identify gaps',
      'Build the template and create a 5-minute demo video showing real use cases',
      'Upload to Gumroad (10% fee) or Lemon Squeezy (5% + 50¢ fee)',
      'Post helpful content on Twitter/X and YouTube—not just sales pitches',
    ],
    resources: [
      { title: 'Notion Formula Documentation', type: 'article' },
      { title: 'Template Design Best Practices', type: 'article' },
      { title: 'Gumroad Creator Guide', type: 'video' },
    ],
    competition: 'medium',
    demandTrend: 'stable',
    riskLevel: 'low',
    whyThisOpportunity: 'Notion has 100M+ users, and template marketplaces are still relatively unsophisticated. Generic templates are oversaturated, but specific workflows for defined audiences consistently sell. The upfront work is significant, but once created, sales are mostly passive with minimal customer support.',
    timeToFirstRevenue: '4-8 weeks',
  },
  {
    id: '6',
    title: 'Mid-Century Furniture Restoration',
    description: 'Find solid wood furniture from the 1950s-1970s, restore and resell to vintage enthusiasts. Focus on recognizable brands and clean lines that are currently in style.',
    category: 'reselling',
    difficulty: 'beginner',
    timeCommitment: 'weekend-only',
    estimatedEarning: { min: 500, max: 1800, period: 'month' },
    startupCost: { min: 150, max: 400 },
    trending: true,
    trendingScore: 78,
    tags: ['Furniture', 'DIY', 'Vintage', 'Creative'],
    createdAt: '2026-03-08',
    keyInsights: [
      'Facebook Marketplace has constant free furniture listings',
      'Danish and Scandinavian pieces command 3-5x premiums',
      'Chalk paint technique requires minimal prep—perfect for beginners',
    ],
    steps: [
      'Set up Facebook Marketplace alerts for keywords: mid-century, Danish, solid wood',
      'Learn to identify quality construction (dovetail joints, solid wood vs veneer)',
      'Buy supplies: sandpaper, chalk paint, clear wax, basic hardware',
      'Document before/after process for social media content',
      'Sell locally via Facebook Marketplace or Nextdoor to avoid shipping',
    ],
    resources: [
      { title: 'Mid-Century Furniture Identification Guide', type: 'article' },
      { title: 'Annie Sloan Chalk Paint Techniques', type: 'video' },
      { title: 'Hardware Replacement Suppliers', type: 'tool' },
    ],
    competition: 'medium',
    demandTrend: 'stable',
    riskLevel: 'low',
    whyThisOpportunity: 'Landfills receive 12 million tons of furniture annually, much of it solid wood that just needs cosmetic work. Millennials and Gen Z prefer vintage over fast furniture for environmental and aesthetic reasons. Weekend schedule makes it perfect for supplementary income.',
    timeToFirstRevenue: '2-3 weeks',
  },
  {
    id: '7',
    title: 'Simple Index Fund Investing',
    description: 'Start a consistent investment habit using low-cost index funds. Not a quick win, but the most reliable path to long-term wealth building for beginners.',
    category: 'investing',
    difficulty: 'beginner',
    timeCommitment: 'flexible',
    estimatedEarning: { min: 0, max: 0, period: 'month' },
    startupCost: { min: 100, max: 1000 },
    trending: false,
    trendingScore: 65,
    tags: ['Investing', 'Long-term', 'Wealth Building', 'Passive'],
    createdAt: '2026-03-05',
    keyInsights: [
      'Historical stock market average return: ~10% annually before inflation',
      'Starting at 25 vs 35 can mean 2x more money at retirement',
      '90% of actively managed funds fail to beat index funds over 15 years',
    ],
    steps: [
      'Open account at Fidelity, Schwab, or Vanguard (no minimums, low fees)',
      'Choose core holding: VTI (total US stock market) or VOO (S&P 500)',
      'Set up automatic investment—$50/week is $2,600/year plus growth',
      'Ignore market news and stay consistent regardless of market conditions',
      'Revisit and rebalance annually, not daily',
    ],
    resources: [
      { title: 'JL Collins Stock Series (Free Blog)', type: 'article' },
      { title: 'Bogleheads Investment Philosophy', type: 'article' },
      { title: 'Compound Interest Calculator', type: 'tool' },
    ],
    competition: 'low',
    demandTrend: 'stable',
    riskLevel: 'medium',
    whyThisOpportunity: 'This is not a side hustle—it is wealth building. Most people procrastinate investing because it feels complex. Starting with any amount and automating it removes decision fatigue. The earlier you begin, the more powerful compound growth becomes.',
    timeToFirstRevenue: '10+ years (compound growth)',
  },
  {
    id: '8',
    title: 'TikTok Shop Product Reviewer',
    description: 'Create authentic short-form video reviews of products available on TikTok Shop. Earn commissions when viewers purchase through your links. No inventory or upfront product costs.',
    category: 'trending-products',
    difficulty: 'beginner',
    timeCommitment: 'part-time',
    estimatedEarning: { min: 800, max: 8000, period: 'month' },
    startupCost: { min: 0, max: 200 },
    trending: true,
    trendingScore: 96,
    tags: ['TikTok', 'Affiliate', 'Social Media', 'Video'],
    createdAt: '2026-03-22',
    keyInsights: [
      'TikTok Shop commission rates range from 5% to 30% depending on category',
      'Videos under 60 seconds with genuine reactions perform best',
      'You can request free samples from sellers once you have 1,000 followers',
    ],
    steps: [
      'Apply for TikTok Shop Creator Program (requires 5,000 followers or be US-based)',
      'Choose a niche you genuinely care about (beauty, gadgets, home goods)',
      'Post 1-2 authentic reviews daily using products you already own',
      'Engage with every comment to boost algorithmic distribution',
      'Study trending sounds and formats but keep reviews honest',
    ],
    resources: [
      { title: 'TikTok Shop Creator Academy', type: 'article' },
      { title: 'CapCut Video Editing (Free)', type: 'tool' },
      { title: 'Trending Products Dashboard', type: 'tool' },
    ],
    competition: 'high',
    demandTrend: 'rising',
    riskLevel: 'medium',
    whyThisOpportunity: 'TikTok Shop is the fastest-growing e-commerce platform, and the algorithm currently prioritizes shop content with extra distribution. Unlike traditional affiliate marketing, you do not need a website—just authentic video content. Early adopters are seeing significant reach before the space becomes saturated.',
    timeToFirstRevenue: '3-6 weeks',
  },
  {
    id: '9',
    title: 'Turo Car Sharing Host',
    description: 'List your personal vehicle on Turo when you are not using it. Turn an depreciating asset into a revenue generator with built-in insurance protection.',
    category: 'side-hustle',
    difficulty: 'beginner',
    timeCommitment: 'flexible',
    estimatedEarning: { min: 400, max: 1800, period: 'month' },
    startupCost: { min: 0, max: 300 },
    trending: true,
    trendingScore: 79,
    tags: ['Sharing Economy', 'Passive', 'Automotive', 'Asset Optimization'],
    createdAt: '2026-03-18',
    keyInsights: [
      'The average car sits idle 95% of the time',
      'Luxury and unique vehicles earn $75-200/day vs $35-50 for economy cars',
      'Turo provides $750,000 liability insurance and physical damage protection',
    ],
    steps: [
      'Check if your car qualifies (model year 2008 or newer, under 130,000 miles)',
      'Review your personal auto insurance policy for any restrictions',
      'Take high-quality photos in good lighting showing all angles',
      'Set competitive pricing using Turo automatic pricing tool as baseline',
      'Respond to booking requests within 1 hour to improve search ranking',
    ],
    resources: [
      { title: 'Turo Host Calculator', type: 'tool' },
      { title: 'Host Protection Plan Details', type: 'article' },
      { title: 'Pricing Strategy for Your Market', type: 'video' },
    ],
    competition: 'medium',
    demandTrend: 'rising',
    riskLevel: 'medium',
    whyThisOpportunity: 'Car payments average $500-700/month, yet most vehicles sit unused. Turo allows you to offset ownership costs or generate profit. Platform insurance protects you, and traveler demand is consistently growing as people seek alternatives to traditional rental car companies.',
    timeToFirstRevenue: '1-2 weeks',
  },
  {
    id: '10',
    title: 'AI Professional Headshots Service',
    description: 'Create polished AI-generated headshots for job seekers, LinkedIn users, and corporate teams. Deliver in hours instead of weeks at a fraction of traditional photography costs.',
    category: 'ai-opportunities',
    difficulty: 'beginner',
    timeCommitment: 'part-time',
    estimatedEarning: { min: 1200, max: 4000, period: 'month' },
    startupCost: { min: 50, max: 150 },
    trending: true,
    trendingScore: 88,
    tags: ['AI', 'Photography', 'Digital Service', 'B2C'],
    createdAt: '2026-03-19',
    keyInsights: [
      'Traditional professional headshots cost $200-500 and require scheduling',
      'AI services typically charge $25-75 per person with 1-hour delivery',
      'Corporate team packages (10+ people) are the most profitable segment',
    ],
    steps: [
      'Master Midjourney or specialized headshot AI tools like Aragon.ai',
      'Create diverse sample portfolio showing different professional styles',
      'Set up simple booking page using Calendly + Stripe or Stan Store',
      'Target job seekers on LinkedIn and corporate HR departments',
      'Offer package tiers: Basic (3 photos), Professional (10 photos), Executive (20+ photos)',
    ],
    resources: [
      { title: 'Midjourney Portrait Photography Guide', type: 'video' },
      { title: 'AI Headshot Prompt Library', type: 'tool' },
      { title: 'Pricing Strategy for Photo Services', type: 'article' },
    ],
    competition: 'medium',
    demandTrend: 'rising',
    riskLevel: 'low',
    whyThisOpportunity: 'Everyone needs a professional headshot for LinkedIn, company websites, and speaking engagements. Traditional photography is expensive and time-consuming. AI-generated headshots have reached quality levels that satisfy most professional needs at a fraction of the cost and time.',
    timeToFirstRevenue: '1-3 weeks',
  },
  {
    id: '11',
    title: 'Virtual Assistant for E-commerce Sellers',
    description: 'Help Amazon FBA and Shopify store owners with customer service, listing optimization, and order management. High demand for reliable English-speaking VAs.',
    category: 'freelancing',
    difficulty: 'beginner',
    timeCommitment: 'part-time',
    estimatedEarning: { min: 1500, max: 4000, period: 'month' },
    startupCost: { min: 0, max: 200 },
    trending: true,
    trendingScore: 84,
    tags: ['Remote Work', 'E-commerce', 'Virtual Assistant', 'Entry Level'],
    createdAt: '2026-03-14',
    keyInsights: [
      'E-commerce sellers typically pay $15-25/hour for US-based VAs',
      'Most sellers need 10-20 hours weekly of support',
      'Specializing in Amazon or Shopify increases rates by 30-50%',
    ],
    steps: [
      'Learn basics of Amazon Seller Central or Shopify admin (free tutorials available)',
      'Create profile on Upwork, OnlineJobs.ph, or specialized VA marketplaces',
      'Offer first client a trial week at discounted rate to build reviews',
      'Develop systems for common tasks (response templates, SOPs)',
      'Ask satisfied clients for referrals—word of mouth is strongest in this space',
    ],
    resources: [
      { title: 'Amazon Seller Central Training', type: 'video' },
      { title: 'VA Client Onboarding Templates', type: 'tool' },
      { title: 'Upwork Profile Optimization Guide', type: 'article' },
    ],
    competition: 'medium',
    demandTrend: 'rising',
    riskLevel: 'low',
    whyThisOpportunity: 'E-commerce continues growing, and sellers are overwhelmed with operational tasks. Many prefer US-based VAs for customer-facing work despite higher costs than overseas alternatives. The barrier to entry is low—basic computer skills and reliability are the main requirements.',
    timeToFirstRevenue: '2-4 weeks',
  },
  {
    id: '12',
    title: 'Google Business Profile Optimization',
    description: 'Help local businesses rank higher in Google Maps by optimizing their Google Business Profiles. Most small businesses have incomplete or neglected profiles.',
    category: 'local-demand',
    difficulty: 'beginner',
    timeCommitment: 'part-time',
    estimatedEarning: { min: 1000, max: 3500, period: 'month' },
    startupCost: { min: 0, max: 100 },
    trending: true,
    trendingScore: 82,
    tags: ['Local SEO', 'Google', 'Small Business', 'Digital Marketing'],
    createdAt: '2026-03-12',
    keyInsights: [
      '46% of Google searches are looking for local information',
      'Businesses in top 3 map results get 60% of clicks',
      'One-time optimization fee: $300-800. Monthly management: $200-500',
    ],
    steps: [
      'Learn Google Business Profile optimization fundamentals (free Google resources)',
      'Identify local businesses ranking poorly (page 2+ of maps results)',
      'Audit their profiles and create a short improvement report',
      'Send cold email with specific issues you found and your fix proposal',
      'Focus on high-value niches: dentists, lawyers, home services',
    ],
    resources: [
      { title: 'Google Business Profile Help Center', type: 'article' },
      { title: 'Local SEO Checklist', type: 'tool' },
      { title: 'Cold Email Templates for Local Businesses', type: 'article' },
    ],
    competition: 'medium',
    demandTrend: 'rising',
    riskLevel: 'low',
    whyThisOpportunity: 'Google Maps is the primary way customers find local businesses, yet most small business owners have never optimized their profiles. The work is straightforward but time-consuming for business owners. Results are measurable—rankings improve within 2-4 weeks, making it easy to prove value.',
    timeToFirstRevenue: '2-4 weeks',
  },
];

export const userProfile: UserProfile = {
  id: 'user-1',
  name: 'Alex Chen',
  email: 'alex@example.com',
  interests: ['side-hustles', 'online-business', 'investing'],
  savedOpportunities: ['1', '3', '5'],
  completedOpportunities: [],
  joinedAt: '2026-03-01',
  region: 'United States',
  notificationsEnabled: true,
  darkModeEnabled: true,
};
